events {}
http {
  upstream api {
    server user-service:5000;
    server auth-service:8081;
    server map-service:8082;
    server feedback-service:8083;
  }

  server {
    listen 80;
    location /api/ {
      proxy_pass http://api;
    }
  }
}
